# Generated by Django 5.1.2 on 2024-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
