# Generated by Django 5.1.2 on 2024-11-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount',
        ),
    ]
