# Generated by Django 5.1.2 on 2024-11-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventamount_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='terms_and_conditions',
        ),
    ]
