# Generated by Django 5.1.2 on 2024-11-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventregistration_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
