# Generated by Django 5.1.2 on 2024-12-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventamount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10),
        ),
    ]
