# Generated by Django 4.2.6 on 2024-12-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_modified_by_eventamount_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='already_iyf_member',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='section_category',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_church_member',
            field=models.BooleanField(default=True, max_length=3),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='nation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
