# Generated by Django 4.2.6 on 2025-01-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0005_remove_branch_area'),
        ('events', '0010_eventregistration_church_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.branch'),
        ),
    ]
