# Generated by Django 4.2.6 on 2024-08-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('account_management_list_groups_and_roles', 'view groups and roles'), ('account_management_create_group_and_assign_roles', 'create new groups and assign roles'), ('account_management_update_groups_and_roles', 'update existing groups and their roles'), ('account_management_create_admin', 'create a new admin'), ('account_management_list_admins', 'view admins'), ('account_management_delete_admin', 'delete admin'), ('account_management_update_admin', 'update admin'), ('member_management_list_members', 'view members'), ('member_management_update_member', 'update an existing member'), ('member_management_create_member', 'add a new member'), ('member_management_delete_member', 'delete a member')]},
        ),
    ]
