# Generated by Django 4.2.6 on 2024-12-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
