version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - SERVICE_TYPE=web
      - ENVIRONMENT=local
    networks:
      - app_network

networks:
  app_network:
    driver: bridge