# Generated by Django 4.2.6 on 2024-08-30 22:47

import apps.shared.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='communication_preferences',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS')], default='sms', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='educational_level',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_baptised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('singe', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(12, 'Phone number number must be at least 14 characters.'), apps.shared.utils.validators.validate_only_digits]),
        ),
        migrations.AlterField(
            model_name='member',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
