# Generated by Django 4.2.6 on 2024-08-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('member', '0003_alter_member_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.customtypes'),
        ),
    ]
