# Generated by Django 4.2.6 on 2024-08-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('member', '0004_member_member_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_group',
            field=models.ManyToManyField(blank=True, related_name='member_group', to='shared.customtypes'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_position', to='shared.customtypes'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_type', to='shared.customtypes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_title', to='shared.customtypes'),
        ),
    ]
