# Generated by Django 4.2.6 on 2024-09-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_member_group_member_member_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
