# Generated by Django 5.1.2 on 2024-10-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_count',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='likes',
        ),
    ]
