# Generated by Django 5.1.2 on 2024-12-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_userinteraction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
