# Generated by Django 4.2.6 on 2024-12-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0005_remove_branch_area'),
        ('content', '0005_post_modified_by_postmedia_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.branch'),
        ),
    ]
