# Generated by Django 4.2.6 on 2024-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtypes',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
