# Generated by Django 5.1.2 on 2024-11-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_user_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reference_number',
            new_name='reference',
        ),
    ]
