# Generated by Django 5.1.2 on 2024-11-17 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_reference_number_transaction_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='PaymentTransaction',
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'PaymentTransaction', 'verbose_name_plural': 'PaymentTransactions'},
        ),
    ]
