# Generated by Django 4.2.6 on 2024-08-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('jurisdiction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_head', to='member.member'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_head', to='member.member'),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_head', to='member.member'),
        ),
    ]
