# Generated by Django 4.2.6 on 2024-08-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0003_alter_area_area_head_alter_branch_branch_head_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='map_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='map_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
