# Generated by Django 5.1.2 on 2024-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_pledge_is_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
