# Generated by Django 5.1.2 on 2024-11-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_pledge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='date',
            field=models.DateField(),
        ),
    ]
