# Generated by Django 5.1.2 on 2024-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_alter_pledge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='redeemed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
