# Generated by Django 5.1.2 on 2024-11-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_pledge_redeemed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='date',
            new_name='redeem_date',
        ),
    ]
